### ISSUE TITLE
2021-06-04 开源项目的 issues 应该谁来关闭？

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/inspiration-study-zh#2]
# 主题类型

> 以下主题可以多选

* [x] 技术
* [x] 开源
* [ ] 文档
* [ ] 软技能
* [ ] 沟通

# 概要

* 简单概述自身参与的开源项目在 issues 管理的经验
* 自由讨论

# 时间

8 PM ~ 8:30 PM

# 会议链接

已完成✅

# 分享人

@LinuxSuRen 

> 对该话题有兴趣的请添加标签或者留言！

**Comment by JohnNiang** [comment]
Let me in : P

**Comment by fengzhao** [comment]
应该是由issue的提出者来关闭比较合适

**Comment by liangyuanpeng** [comment]
repo相关负责人应该推进issue的进度(打label或即使更新信息),当长时间issue没有任何更新时, 负责人可以暂时关闭issue,同时说明如果issue提出者对当前issue还有任何问题可以reopen.

**Comment by caojiele** [comment]
通常contributor pre commit 时，会关联对应的issue编号，当commitor merge pre 后，会自动关闭对应的issue；其次如果没有相应的关闭，最好是issue的提出者关闭。

**Comment by LinuxSuRen** [comment]
交流已完成，现关闭该 issue
